# Copyright (c) 2026 Ankerin
# SPDX-License-Identifier: MIT

[package]
name = "daemon"
description = "AstroLune node daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
telemetry = { version = "0.1.0", path = "../../crates/telemetry" }
codec = { version = "0.1.0", path = "../../crates/codec" }
config = { version = "0.1.0", path = "../../crates/config" }
consensus = { version = "0.1.0", path = "../../crates/consensus" }
crypto = { version = "0.1.0", path = "../../crates/crypto" }
genesis = { version = "0.1.0", path = "../../crates/genesis" }
keystore = { version = "0.1.0", path = "../../crates/keystore" }
zeroize = "=1.9.0"
node = { version = "0.1.0", path = "../../crates/node" }
p2p = { version = "0.1.0", path = "../../crates/p2p" }
rpc = { version = "0.1.0", path = "../../crates/rpc" }
state = { version = "0.1.0", path = "../../crates/state" }
storage = { version = "0.1.0", path = "../../crates/storage" }
types = { version = "0.1.0", path = "../../crates/types" }

[dev-dependencies]
p2p = { version = "0.1.0", path = "../../crates/p2p", features = ["provisioning"] }
execution = { version = "0.1.0", path = "../../crates/execution" }
transaction = { version = "0.1.0", path = "../../crates/transaction" }

[lints]
workspace = true
