# Copyright (c) 2026 Astrolune contributors
# SPDX-License-Identifier: MIT

[package]
name = "dns"
description = "AstroLune in-network DNS service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
consensus = { version = "0.1.0", path = "../../crates/consensus" }
contract-sdk = { version = "0.1.0", path = "../../crates/contract-sdk", default-features = false }
codec = { version = "0.1.0", path = "../../crates/codec" }
genesis = { version = "0.1.0", path = "../../crates/genesis" }
rpc = { version = "0.1.0", path = "../../crates/rpc" }
runtime = { version = "0.1.0", path = "../../crates/runtime" }
transaction = { version = "0.1.0", path = "../../crates/transaction" }
types = { version = "0.1.0", path = "../../crates/types" }

[dev-dependencies]
crypto = { version = "0.1.0", path = "../../crates/crypto" }
state = { version = "0.1.0", path = "../../crates/state" }
wat = "=1.261.0"

[lints]
workspace = true
