# Copyright (c) 2026 Ankerin
# SPDX-License-Identifier: MIT

[package]
name = "codec-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[workspace]

[features]
windows-coverage = []

[build-dependencies]
cc = "1"

[dependencies]
crypto = { path = "../../crypto" }
rpc = { path = "../../rpc" }
storage = { path = "../../storage" }
p2p = { path = "../../p2p" }
runtime = { path = "../../runtime" }
contract-sdk = { path = "../../contract-sdk", default-features = false }
libfuzzer-sys = "0.4.13"
types = { path = "../../types" }
state = { path = "../../state" }
genesis = { path = "../../genesis" }
consensus = { path = "../../consensus" }
node = { path = "../../node" }

[[bin]]
name = "decode_network"
path = "fuzz_targets/decode_network.rs"
test = false
doc = false

[[bin]]
name = "decode_consensus"
path = "fuzz_targets/decode_consensus.rs"
test = false
doc = false

[dependencies.codec]
path = ".."

[[bin]]
name = "decode_genesis"
path = "fuzz_targets/decode_genesis.rs"
test = false
doc = false

[[bin]]
name = "decode_state_absence"
path = "fuzz_targets/decode_state_absence.rs"
test = false
doc = false

[[bin]]
name = "decode_state_snapshot"
path = "fuzz_targets/decode_state_snapshot.rs"
test = false
doc = false

[[bin]]
name = "decode_execution_receipt"
path = "fuzz_targets/decode_execution_receipt.rs"
test = false
doc = false

[[bin]]
name = "decode_transaction"
path = "fuzz_targets/decode_transaction.rs"
test = false
doc = false

[[bin]]
name = "decode_block_header"
path = "fuzz_targets/decode_block_header.rs"
test = false
doc = false

[[bin]]
name = "decode_hash256"
path = "fuzz_targets/decode_hash256.rs"
test = false
doc = false

[[bin]]
name = "decode_address"
path = "fuzz_targets/decode_address.rs"
test = false
doc = false

[[bin]]
name = "decode_resources"
path = "fuzz_targets/decode_resources.rs"
test = false
doc = false

[[bin]]
name = "decode_state_key"
path = "fuzz_targets/decode_state_key.rs"
test = false
doc = false

[[bin]]
name = "decode_validator_id"
path = "fuzz_targets/decode_validator_id.rs"
test = false
doc = false

[[bin]]
name = "decode_extensions"
path = "fuzz_targets/decode_extensions.rs"
test = false
doc = false

[[bin]]
name = "execute_contract"
path = "fuzz_targets/execute_contract.rs"
test = false
doc = false
