# Copyright (c) 2026 Ankerin
# SPDX-License-Identifier: MIT

[package]
name = "state"
description = "Versioned state interfaces for AstroLune"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
codec = { version = "0.1.0", path = "../codec" }
crypto = { version = "0.1.0", path = "../crypto" }
types = { version = "0.1.0", path = "../types" }

[dev-dependencies]
testkit = { version = "0.1.0", path = "../testkit" }

[[bench]]
name = "state"
harness = false

[lints]
workspace = true
