# Copyright (c) 2026 Ankerin
# SPDX-License-Identifier: MIT

[workspace]
resolver = "3"
members = [
    "apps/cli",
    "apps/daemon",
    "crates/codec",
    "crates/config",
    "crates/consensus",
    "crates/contract-sdk",
    "crates/contract-abi",
    "crates/crypto",
    "crates/execution",
    "crates/genesis",
    "crates/keystore",
    "crates/mempool",
    "crates/node",
    "crates/p2p",
    "crates/rpc",
    "crates/runtime",
    "crates/state",
    "crates/storage",
    "crates/sync",
    "crates/telemetry",
    "crates/testkit",
    "crates/transaction",
    "crates/types",
    "services/dns",
    "tests/integration",
    "tools/cargo-contract",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.99"
license = "MIT"
authors = ["Ankerin"]
repository = "https://github.com/astrolune-network/astrolune"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
