# Copyright (c) 2026 Ankerin
# SPDX-License-Identifier: MIT

[toolchain]
channel = "1.99.0"
components = [ "clippy", "rustfmt", "rust-analyzer" ]
profile = "minimal"
targets = ["wasm32-unknown-unknown"]
