# Copyright (c) 2026 Astrolune contributors
# SPDX-License-Identifier: MIT

[package]
name = "node"
description = "AstroLune node pipeline coordination"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
codec = { version = "0.1.0", path = "../codec" }
crypto = { version = "0.1.0", path = "../crypto" }
consensus = { version = "0.1.0", path = "../consensus" }
execution = { version = "0.1.0", path = "../execution" }
genesis = { version = "0.1.0", path = "../genesis" }
keystore = { version = "0.1.0", path = "../keystore" }
mempool = { version = "0.1.0", path = "../mempool" }
p2p = { version = "0.1.0", path = "../p2p" }
state = { version = "0.1.0", path = "../state" }
storage = { version = "0.1.0", path = "../storage" }
transaction = { version = "0.1.0", path = "../transaction" }
types = { version = "0.1.0", path = "../types" }

[lints]
workspace = true

[dev-dependencies]
wat = "=1.261.0"
