# Copyright (c) 2026 Ankerin
# SPDX-License-Identifier: MIT

[package]
name = "rpc"
description = "External application API boundaries for AstroLune"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
storage = { version = "0.1.0", path = "../storage" }
state = { version = "0.1.0", path = "../state" }
genesis = { version = "0.1.0", path = "../genesis" }
consensus = { version = "0.1.0", path = "../consensus" }
codec = { version = "0.1.0", path = "../codec" }
types = { version = "0.1.0", path = "../types" }

[dev-dependencies]
crypto = { version = "0.1.0", path = "../crypto" }

[lints]
workspace = true
