# Copyright (c) 2026 Ankerin
# SPDX-License-Identifier: MIT

[package]
name = "execution"
description = "Deterministic parallel execution interfaces for AstroLune"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
runtime = { version = "0.1.0", path = "../runtime" }
codec = { version = "0.1.0", path = "../codec" }
state = { version = "0.1.0", path = "../state" }
transaction = { version = "0.1.0", path = "../transaction" }
types = { version = "0.1.0", path = "../types" }

[dev-dependencies]
wat = "=1.261.0"
crypto = { version = "0.1.0", path = "../crypto" }

[lints]
workspace = true
