# Copyright (c) 2026 Ankerin
# SPDX-License-Identifier: MIT

[package]
name = "contract-sdk"
description = "Rust smart-contract SDK primitives for AstroLune"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
crate-type = ["rlib"]

[features]
default = ["alloc"]
alloc = []

[dependencies]
contract-abi = { version = "0.1.0", path = "../contract-abi" }

[lints]
workspace = true
