# Copyright (c) 2026 Astrolune contributors
# SPDX-License-Identifier: MIT

[package]
name = "cli"
description = "AstroLune operator and developer command-line interface"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
storage = { version = "0.1.0", path = "../../crates/storage" }
node = { version = "0.1.0", path = "../../crates/node" }
runtime = { version = "0.1.0", path = "../../crates/runtime" }
codec = { version = "0.1.0", path = "../../crates/codec" }
config = { version = "0.1.0", path = "../../crates/config" }
consensus = { version = "0.1.0", path = "../../crates/consensus" }
crypto = { version = "0.1.0", path = "../../crates/crypto" }
execution = { version = "0.1.0", path = "../../crates/execution" }
genesis = { version = "0.1.0", path = "../../crates/genesis" }
keystore = { version = "0.1.0", path = "../../crates/keystore" }
p2p = { version = "0.1.0", path = "../../crates/p2p", features = ["provisioning"] }
rpc = { version = "0.1.0", path = "../../crates/rpc" }
state = { version = "0.1.0", path = "../../crates/state" }
transaction = { version = "0.1.0", path = "../../crates/transaction" }
types = { version = "0.1.0", path = "../../crates/types" }
zeroize = "1.9.0"

[lints]
workspace = true

[dev-dependencies]
wat = "=1.261.0"
