# Copyright (c) 2026 Ankerin
# SPDX-License-Identifier: MIT

[package]
name = "crypto"
description = "Cryptographic provider implementations for AstroLune"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
blake2 = "=0.11.0"
ed25519-dalek = "=3.0.0"
vrf-rfc9381 = { version = "=0.0.7", default-features = false, features = ["edwards25519"] }
zeroize = "=1.9.0"
types = { version = "0.1.0", path = "../types" }

[dev-dependencies]
testkit = { version = "0.1.0", path = "../testkit" }

[[bench]]
name = "crypto"
harness = false

[lints]
workspace = true
